name: C Build-Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make test
      run: cd examples && make test

